---
title: "draw mht for DMR"
output: html_document
date: "2025-05-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#load data
```{r}
data50 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p default//resu_ipdmr.csv")
data100 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 100//resu_ipdmr.csv")
data200 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 200//resu_ipdmr.csv")
data300 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 300//resu_ipdmr.csv")
data400 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 400//resu_ipdmr.csv")
data500 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 500//resu_ipdmr.csv")
data800 <- read.csv("C://Users//Administrator//Documents//DMR without chrM//p 800//resu_ipdmr.csv")
data50f<- read.csv("C://Users//Administrator//Documents//resu_ipdmr.csv")

```

#function
```{r}
library(ggplot2)
library(dplyr)

mhtplot_ggplot <- function(probe = NULL, chr, start, p, col = "bg", sigthre = c(0.05, 0.01),
                           outf = "mht", outfmt = "jpg", ...) {
  
  chr_levels <- c(as.character(1:22), "X", "Y")
  
  if (!is.null(probe)) {
    formatted_data_p <- data.frame(probe = probe, chr = chr, start = start, p = p)
  } else {
    formatted_data_p <- data.frame(chr = chr, start = start, p = p)
  }
  
  formatted_data_p <- formatted_data_p %>%
    mutate(chr = as.character(chr)) %>%
    filter(chr %in% chr_levels) %>%
    mutate(chr = factor(chr, levels = chr_levels))
  
  formatted_data_p <- formatted_data_p %>%
    mutate(neglog10p = -log10(p)) %>%
    arrange(chr, start)
  
  color_palette <- c("red", "blue", "green", "purple", "orange", "cyan")
  if (col == "bg") {
    formatted_data_p$color <- color_palette[as.numeric(formatted_data_p$chr) %% length(color_palette) + 1]
  } else {
    formatted_data_p$color <- col
  }
  
  chr_positions <- formatted_data_p %>%
    group_by(chr) %>%
    summarise(chr_len = max(start)) %>%
    arrange(factor(chr, levels = chr_levels)) %>%
    mutate(tot = cumsum(as.numeric(chr_len)) - chr_len) %>%
    select(-chr_len)
  
  formatted_data_p <- formatted_data_p %>%
    left_join(chr_positions, by = "chr") %>%
    arrange(chr, start) %>%
    mutate(BPcum = start + tot)
  
  axisdf <- formatted_data_p %>%
    group_by(chr) %>%
    summarize(center = (max(BPcum) + min(BPcum)) / 2) %>%
    arrange(factor(chr, levels = chr_levels))
  
  p_plot <- ggplot(formatted_data_p, aes(x = BPcum, y = neglog10p, color = color)) +
    geom_point(size = 1) +
    scale_color_identity() +
    scale_x_continuous(label = axisdf$chr, breaks = axisdf$center) +
    scale_y_continuous(expand = c(0, 0), limits = c(0, 10)) +
    labs(x = "Chromosome", y = "-log10(P-value)") +
    theme_minimal() +
    theme(
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      axis.text.x = element_text(angle = 45, hjust = 1)
    )
  
  # Add significance lines and labels
  if (!is.null(sigthre)) {
    sig_colors <- c("blue", "red", "black")  # Extendable if needed
    for (i in seq_along(sigthre)) {
      yval <- -log10(sigthre[i])
sig_labels <- c("blue: p = 0.05", "red: p = 0.01")
sig_colors <- c("blue", "red")

x_pos <- max(formatted_data_p$BPcum) * 0.98
y_top <- max(formatted_data_p$neglog10p)

for (i in seq_along(sigthre)) {
  yval <- -log10(sigthre[i])
  
  p_plot <- p_plot +
    geom_hline(yintercept = yval, linetype = "dashed", color = sig_colors[i]) +
    annotate("text",
             x = x_pos,
             y = y_top - (i - 1) * 0.4,
             label = sig_labels[i],
             hjust = 1, vjust = 1,
             color = "black",  # text in black
             size = 3.5)
}


    }
  }
  
  # Save plot
  ggsave(filename = paste0(outf, ".", outfmt), plot = p_plot, device = outfmt, ...)
  
  return(p_plot)
}
```


#draw by function-50
```{r}
mhtplot_ggplot(
  probe = data50$probe,
  chr = data50$chr,
  start = data50$start,
  p = data50$fdr,
  col = "bg",
  sigthre = c(0.05, 0.01),
  outf = "mht_DMR_50",
  outfmt = "jpg",
  width = 10,
  height = 6
)
```



#100
```{r}
mhtplot_ggplot(
  probe = data100$probe,
  chr = data100$chr,
  start = data100$start,
  p = data100$fdr,
  col = "bg",
  sigthre = c(0.05, 0.01),
  outf = "mht_DMR_100",
  outfmt = "jpg",
  width = 10,
  height = 6
)
```
#full DMR(50)
```{r}
mhtplot_ggplot(
  probe = data50f$probe,
  chr = data50f$chr,
  start = data50f$start,
  p = data50f$fdr,
  col = "bg",
  sigthre = c(0.05, 0.01),
  outf = "mht_DMR_50",
  outfmt = "jpg",
  width = 10,
  height = 6
)#warning means there are 1 p value is about 17, which is greater than max y axis
```






















#######try new function
```{r}
library(ggplot2)
library(dplyr)

# Define chromosome order
chr_levels <- c(as.character(1:22), "X", "Y")

# Prepare data
data50 <- data50 %>%
  mutate(chr = as.character(chr)) %>%
  filter(chr %in% chr_levels) %>%
  mutate(chr = factor(chr, levels = chr_levels)) %>%
  arrange(chr, start)

# Calculate cumulative positions
chr_offsets <- data50 %>%
  group_by(chr) %>%
  summarize(chr_len = max(start)) %>%
  arrange(chr) %>%
  mutate(offset = cumsum(lag(chr_len, default = 0)))

data50 <- data50 %>%
  left_join(chr_offsets %>% select(chr, offset), by = "chr") %>%
  mutate(BPcum = start + offset)

# Axis label positions
axisdf <- data50 %>%
  group_by(chr) %>%
  summarize(center = (min(BPcum) + max(BPcum)) / 2)

# Assign alternating colors
chrom_colors <- rep(c("blue", "darkgreen"), length.out = length(chr_levels))

# Create plot
manhattan_plot <- ggplot(data50, aes(x = BPcum, y = -log10(fdr), color = chr)) +
  geom_point(alpha = 0.8, size = 1.2) +
  geom_hline(yintercept = -log10(0.05), linetype = "dashed", color = "red") +
  scale_color_manual(values = chrom_colors) +
  scale_x_continuous(label = axisdf$chr, breaks = axisdf$center) +
  labs(title = "Manhattan Plot: Time Effect",
       x = "Chromosome",
       y = "-log10(FDR)") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5),
        legend.position = "none")

```

```{r}
mhtplot_ggplot(
  probe = data100$probe,
  chr = data100$chr,
  start = data100$start,
  p = data100$fdr,
  col = "bg",
  sigthre = c(0.05, 0.01),
  outf = "mht_DMR_50",
  outfmt = "jpg",
  width = 10,
  height = 6
)
```

















